#pragma once

enum GLYPH_CACHE_LEVEL
{
	NONE,
	GLYPH_RUN,
	SINGLE_GLYPH
};

enum LOCK_TYPE
{
	LOCK_GAMMA,
	LOCK_LINKED_FONT,
	LOCK_LRU,
	LOCK_REG_FONT,
	LOCK_SETTING_CACHE,
	LOCK_DEBUG,

	// count of lock types
	// NEVER use this type
	_LOCK_TYPE_COUNT_
};

enum PIXEL_GEOMETRY_TYPE
{
	PIXEL_GEOMETRY_RGB,
	PIXEL_GEOMETRY_BGR
};

enum RENDERER_TYPE
{
	RENDERER_CLEARTYPE = 0,
	RENDERER_FREETYPE = 10,
	RENDERER_GETGLYPHOUTLINE = 20,
	RENDERER_DIRECTWRITE = 30,
	RENDERER_WIC = 31
};